/-
  Demo Runner - Canopy app linalg tab content.
-/
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.VectorInterpolation
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.VectorArithmetic
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.VectorProjection
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.VectorField
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.VectorField3D
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.CrossProduct3D
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.Matrix2DTransform
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.Matrix3DTransform
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.ProjectionExplorer
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.MatrixDecomposition
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.QuaternionVisualizer
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.SlerpInterpolation
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.EulerGimbalLock
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.DualQuaternionBlending
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.RayCastingPlayground
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.PrimitiveOverlapTester
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.VoronoiDelaunayDual
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.ConvexHull2D
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.ConvexDecomposition
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.TransformHierarchy
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.BarycentricCoordinates
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.FrustumCullingDemo
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.QuadtreeVisualizer
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.OctreeViewer3D
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.BVHRayTracer
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.KDTreeNearestNeighbor
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.ParticleIntegrationComparison
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.CollisionResponseDemo
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.RigidBodySimulator
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.InertiaTensorVisualizer
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.SweptCollisionDemo
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.ConstraintSolver
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.BezierCurveEditor
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.CatmullRomSplineEditor
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.BSplineCurveDemo
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.ArcLengthParameterization
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.BezierPatchSurface
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.EasingFunctionGallery
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.SmoothDampFollower
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.SpringAnimationPlayground
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.NoiseExplorer2D
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.FBMTerrainGenerator
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.DomainWarpingDemo
import Demos.Core.Runner.CanopyApp.Tabs.Linalg.WorleyCellularNoise
import AfferentMath.Widget.VectorField
open AfferentMath.Widget
