/-
  Demos - All demo modules for Afferent
-/
import Demos.Overview.Shapes
import Demos.Overview.Transforms
import Demos.Overview.Strokes
import Demos.Overview.Gradients
import Demos.Overview.Text
import Demos.Overview.Animations
import Demos.Perf.Circles
import Demos.Perf.Sprites
import Demos.Perf.Lines
import Demos.Layout.Flexbox
import Demos.Visuals.ShapeGallery
import Demos.Visuals.LineCaps
import Demos.Visuals.DashedLines
import Demos.Chat.App
import Demos.Linalg.Shared
import Demos.Linalg.VectorInterpolation
import Demos.Linalg.VectorArithmetic
import Demos.Linalg.VectorProjection
import Demos.Linalg.VectorField
import Demos.Linalg.VectorField3D
import Demos.Linalg.CrossProduct3D
import Demos.Linalg.Matrix2DTransform
import Demos.Linalg.Matrix3DTransform
import Demos.Linalg.ProjectionExplorer
import Demos.Linalg.MatrixDecomposition
import Demos.Linalg.QuaternionVisualizer
import Demos.Linalg.SlerpInterpolation
import Demos.Linalg.EulerGimbalLock
import Demos.Linalg.DualQuaternionBlending
import Demos.Linalg.RayCastingPlayground
import Demos.Linalg.PrimitiveOverlapTester
import Demos.Linalg.VoronoiDelaunayDual
import Demos.Linalg.ConvexHull2D
import Demos.Linalg.ConvexDecomposition
import Demos.Linalg.TransformHierarchy
import Demos.Linalg.BarycentricCoordinates
import Demos.Linalg.FrustumCullingDemo
import Demos.Linalg.QuadtreeVisualizer
import Demos.Linalg.OctreeViewer3D
import Demos.Linalg.BVHRayTracer
import Demos.Linalg.KDTreeNearestNeighbor
import Demos.Linalg.ParticleIntegrationComparison
import Demos.Linalg.CollisionResponseDemo
import Demos.Linalg.RigidBodySimulator
import Demos.Linalg.InertiaTensorVisualizer
import Demos.Linalg.SweptCollisionDemo
import Demos.Linalg.ConstraintSolver
import Demos.Linalg.BezierCurveEditor
import Demos.Linalg.CatmullRomSplineEditor
import Demos.Linalg.BSplineCurveDemo
import Demos.Linalg.ArcLengthParameterization
import Demos.Linalg.BezierPatchSurface
import Demos.Linalg.EasingFunctionGallery
import Demos.Linalg.SmoothDampFollower
import Demos.Linalg.SpringAnimationPlayground
import Demos.Core.Runner
import AfferentMath.Widget.VectorField
open AfferentMath.Widget
